config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :posts, only: %i[index create destroy]

  get 'api/posts', to: 'api/api#index'
  get 'api/explore', to: 'api/api#explore'
  get 'api/date/:date_1/:date_2', to: 'api/api#date'
  # post 'api/posts/create', to: 'api/api#create'

  post 'repost', to: 'reposts#create', as: 'repost'
  get 'reposts/:id/new', to: 'reposts#new', as: 'new_repost'

  post 'friends/:friend_id/add', to: 'friends#create', as: 'new_friend'
  delete 'friends/:friend_id', to: 'friends#destroy', as: 'destroy_friend'

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    attr_accessor :repost

    #validates :image_url, presence: true, unless: :repost
    belongs_to :user

    has_one_attached :image_url
    has_many :reposts, class_name: "Post", foreign_key: "repost_id", dependent: :destroy

    scope :posts_for_me, ->(friends) { where(user_id: friends.map {|friend| friend.friend_id}).order(created_at: :desc).includes(:user) }
    scope :explore, -> { all.order(created_at: :desc).includes(:user) }
    scope :friend_posts, ->(id) { where(user_id: id).order(created_at: :desc) }
    scope :search_post, ->(q) { where('content LIKE ?', "%#{q}%").order(created_at: :desc).includes(:user) }


    def repost
        Post.find(self.repost_id) unless self.repost_id.nil?
    end

    def reposted?
        Post.find_by(repost_id: self.id) ? true : false
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :friend_self

  has_many :posts, dependent: :destroy
  has_many :friends, dependent: :destroy


  def friend_self
    Friend.create!(
      user_id: self.id,
      friend_id: self.id
    )
  end

  def is_friend_of(user)
    self.friends.pluck(:friend_id).include?(user.id) ? true : false
  end

  def all_friends
    @friend_ids = self.friends.pluck(:friend_id)

    @friends = []

    @friend_ids.each do |friend_id|
      @friends << User.find(friend_id)
    end

    return @friends
  end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::API
    before_action :authenticate_user!

    def index
        @posts = Post.posts_for_me(current_user.friends)

        render json: @posts
    end

    def explore
        @posts = Post.explore

        render json: @posts
    end

    def date
        @posts = Post.where(
            'created_at BETWEEN ? AND ?',
            params[:date_1].to_date.beginning_of_day,
            params[:date_2].to_date.end_of_day
        )

        render json: @posts
    end

    def create
        @post = Post.new(
            image_url: params[:image_url],
            content: params[:content],
            user_id: current_user.id
        )

        if @post.save
            render json: { message: 'El post ha sido creado'}
        else
            render json: { error: 'No se pudo crear el post' }
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def create
    @friend = User.find(params[:friend_id])

    @friendship = Friend.new(
                user_id: current_user.id,
                friend_id: @friend.id
              )

    current_user.friends << @friendship

    redirect_to root_path, notice: "Ahora estás siguiendo a #{@friend.name}"
  end

  def destroy
    @friend = User.find(params[:friend_id])
    
    @friendship = Friend.find_by(user_id: current_user.id, friend_id: @friend.id)

    @friendship.destroy

    redirect_to root_path, notice: "Dejaste de seguir a #{@friend.name}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.posts_for_me(current_user.friends).page(params[:page])
    @posts = Post.explore.page(params[:page]) if params[:explore]
    @posts = Post.friend_posts(params[:id]).page(params[:page]) if params[:id]
    @posts = Post.search_post(params[:q]).page(params[:page]) if params[:q]
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to root_path, notice: 'El post fue creado con éxito!'
    else
      redirect_to root_path, alert: 'No se ha podido crear la publicación, revisa los campos del formulario'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    
    if @post.user == current_user
      @post.destroy
      redirect_to root_path, notice: 'La publicación fue eliminada'
    else
      redirect_to root_path, alert: 'No puedes eliminar una publicación que no es tuya'
    end
  end

  private
  def post_params
    params.require(:post).permit(:image_url, :content)
  end
end

app/controllers/reposts_controller.rb
class RepostsController < ApplicationController

    def new
        @repost = Post.new
        @post = Post.find(params[:id])
    end

    def create
        @repost = Post.new(repost_params)
        @repost.user = current_user

        if @repost.save
            redirect_to root_path, notice: 'Publicación compartida'
        else
            redirect_to root_path, alert: 'No se ha podido compartir la publicación'
        end
    end

    private
    def repost_params
        params.require(:post).permit(:content, :repost_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/friends/create.html.erb
<h1>Friends#create</h1>
<p>Find me in app/views/friends/create.html.erb</p>

app/views/friends/destroy.html.erb
<h1>Friends#destroy</h1>
<p>Find me in app/views/friends/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instafotos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'shared/navbar' %>

    <div class="container main-page">
      <%= render 'shared/message', message: notice, type: 'success' if notice %>
      <%= render 'shared/message', message: alert, type: 'danger' if alert %>
      
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/posts/_new.html.erb
<div class="text-center mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
        
            <%= form_with(model: @post, local: true) do |f| %>

                <% if @post.errors.any? %>
                    <%= render 'shared/errors', errors: @post.errors.full_messages %>
                <% end %>

                <div class="form-group">
                    <%= f.file_field :image_url, class: 'form-control', placeholder: 'imagen' %>
                </div>

                <div class="form-group">
                    <%= f.text_area :content, class: 'form-control', rows: 3, placeholder: 'descripcion' %>
                </div>

                <div>
                    <%= f.submit 'Publicar', class: 'btn btn-cream' %>
                </div>
            <% end %>

        </div>
    </div>
</div>

app/views/posts/index.html.erb
<% unless params[:explore] %>
    <%= render 'new', post: @post %>
<% else %>
    <h2 class="text-center">Explorar</h2>
<% end %>

<% if @posts.length < 1 %>

    <div class="row">
        <div class="col-md-3">
            <%= render 'shared/friends' %>
        </div>

        <div class="col-md-6">
            <div class="text-center mt-5">
                <h1>No hay publicaciones aún</h1>
                <p>Sé el primero!</p>
            </div>    
        </div>
    </div>
    
<% else %>
    
    <div class="row my-3">

        <div class="col-md-3">
            <%= render 'shared/friends' %>
        </div>

        <div class="col-md-6">

            <% @posts.each do |post| %>
                <% if post.repost_id.nil? %>
                    <%= render 'shared/card', post: post %>            
                <% else %>

                    <div class="card">

                        <h5 class="card-title pt-2 pl-2"><%= post.user.name %>
                            <span class="follow">
                                <% if current_user.is_friend_of(post.user) %>
                                    <%= link_to  "dejar de seguir", destroy_friend_path(post.user), method: :delete unless post.user == current_user %>
                                <% else %>
                                    <%= link_to "seguir", new_friend_path(post.user), method: :post %>
                                <% end %>
                            </span>
                        </h5>

                            <% if post.user == current_user %>
                                <%= link_to raw("&#128465"), post, class: 'trash-icon', method: :delete, data: {confirm: 'Quieres borrar esta publicacion?'} %>
                            <% end %>

                        <div class="card-body">
                            <p class="card-text"><%= post.content %></p>
                        </div>

                        <div class="ml-5 mb-2 mr-2">
                            <%= render 'shared/card', post: post.repost %> 
                        </div>

                    </div>
                <% end %>
            <% end %>

            <div class="text-center">
                <%= link_to_next_page @posts, 'Más fotos' %>
            </div>

        </div>    
    </div>

<% end %>

app/views/posts/new.html.erb
<div class="text-center mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">

            <h2>Nueva publicación</h2>
        
            <%= form_with(model: @post, local: true) do |f| %>

                <% if @post.errors.any? %>
                    <%= render 'shared/errors', errors: @post.errors.full_messages %>
                <% end %>

                <div class="form-group">
                    <%= f.label 'url de la imagen' %>
                    <%= f.text_field :image_url, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= f.label 'descripcion' %>
                    <%= f.text_area :content, class: 'form-control', rows: 4 %>
                </div>

                <div>
                    <%= f.submit 'Guardar', class: 'btn btn-cream' %>
                </div>
            <% end %>

            <%= link_to  "Volver", root_path %>

        </div>
    </div>
</div>

app/views/reposts/new.html.erb
<div class="text-center mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">

            <h2>Compartir publicación</h2>
        
            <%= form_with(model: @repost, url: repost_path, local: true) do |f| %>

                <%= f.hidden_field :repost_id, value: @post.id %>
                <%= f.hidden_field :repost, value: true %>

                <% if @post.errors.any? %>
                    <%= render 'shared/errors', errors: @repost.errors.full_messages %>
                <% end %>

                <div class="form-group">
                    <%= f.label 'descripcion' %>
                    <%= f.text_area :content, class: 'form-control', rows: 4 %>
                </div>

                <%= render  "shared/card", post: @post %>

                <div>
                    <%= f.submit 'Guardar', class: 'btn btn-cream' %>
                </div>
            <% end %>

        </div>
    </div>
</div>

app/views/shared/_card.html.erb
<div class="card my-2">
    
    <h5 class="card-title pt-2 pl-2"><%= post.user.name %>
        <span class="follow">
            <% if current_user.is_friend_of(post.user) %>
                <%= link_to  "dejar de seguir", destroy_friend_path(post.user), method: :delete unless post.user == current_user %>
            <% else %>
                <%= link_to "seguir", new_friend_path(post.user), method: :post %>
            <% end %>
        </span>
    </h5>

    <% if post.user == current_user %>
        <%= link_to raw("&#128465"), post, class: 'trash-icon', method: :delete, data: {confirm: 'Quieres borrar esta publicacion?'} %>
    <% end %>

    <!-- <img src="<%= post.image_url %>" class="card-img-top" alt="photo" width="100"> -->
    <%= image_tag post.image_url, class: 'card-img-top', alt: 'photo', width: '100' %>

    <div class="card-body">
        <p class="card-text"><%= post.content %></p>
        <%= link_to  "Compartir", new_repost_path(post.id) unless current_page?(new_repost_path(post.id))%>
    </div>
</div>

app/views/shared/_cover.html.erb
<div class="cover d-none d-md-block">
    <div class="cover__title">
        <h2>Comparte tus experiencias!</h2>
    </div>
</div>

app/views/shared/_errors.html.erb
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="alert-heading">Ups! algo salió mal</h4>
    <p>No he podido realizar esta tarea, revisa los siguientes errores: </p>
        <ul class="list-group">
            <% errors.each do |error| %>
                <li class="list-group-item list-group-item-danger"><%= error %></li>
            <% end %>
        </ul>
    <hr>
    <p class="mb-0">Inténtalo otra vez</p>
</div>

app/views/shared/_footer.html.erb
<footer class="container-fluid d-flex align-items-center justify-content-center bg-cream">
    <h5>Instafotos</h5>
</footer>

app/views/shared/_friends.html.erb
<div class="list-group friend-list">

    <% current_user.all_friends.each do |friend| %>

        <% if friend == current_user %>
            <%= link_to  "Mis publicaciones", root_path(id: friend.id), class: "list-group-item list-group-item-action" %>
        <% else %>
            <%= link_to  "#{friend.name}", root_path(id: friend.id), class: "list-group-item list-group-item-action" %>
        <% end %>
    
    <% end %>

</div>

app/views/shared/_message.html.erb
<div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
    <span><%= message %></span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-cream fixed-top">
    <div class="container">
        <a class="navbar-brand" href="<%= root_path %>">Instafotos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <form class="form-inline my-2 my-lg-0" method="get" action="<%= root_path %>">
                            <input class="form-control mr-sm-2" name="q" type="search" placeholder="Escribe algo..." aria-label="Search">
                            <button class="btn btn-cream my-2 my-sm-0" type="submit">Buscar</button>
                        </form>
                    </li>

                    <li class="nav-item">
                        <%= link_to  "Explorar", root_path(explore: true), class: 'nav-link' %>
                    </li>
                <% end %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= user_signed_in? ? "Bienvenido #{current_user.name}!" : 'Tu cuenta' %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <% if user_signed_in? %>
                            <%= link_to  "Editar perfil", edit_user_registration_path, class:"dropdown-item" %>
                            <%= link_to  "Cerrar sesión", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
                        <% else %>
                            <%= link_to  "Iniciar sesión", new_user_session_path, class:"dropdown-item" %>
                            <%= link_to  "Registrarse", new_user_registration_path, class:"dropdown-item" %>
                        <% end %>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Iniciar sesión", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Registrarse", new_registration_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Olvidaste tu contraseña?", new_password_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%#= link_to "Aún no recibes instrucciones de confirmación?", new_confirmation_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%#= link_to "Aún no recibes instrucciones de desbloqueo?", new_unlock_path(resource_name) %><br />
<%# end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Iniciar sesión con #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>